### ISSUE TITLE
GBIF map not displaying correctly

### ISSUE THREAD

**Issue by StephRorke** [BiologicalRecordsCentre/ukotas#25] opened 2023-02-06 14:27 UTC
Occurrence dots sitting outside of background map in the examples I have checked (Chrome)

![image](https://user-images.githubusercontent.com/35227065/216991713-52cda28c-e79c-42b0-90e8-b8b845d89a07.png)

**Comment by johnvanbreda** [comment] 2024-02-12 16:44
This may have been a problem at the GBIF end - I can't reproduce it now so closing.

**Closed by johnvanbreda** 2024-02-12 16:44 UTC
Labels: bug
